Repository wso2/testgrid, pull requests merged in 2018-03, with the labels that each got.

#541 Fix resolving absolute paths in job-config.yaml
  core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
Labels: Priority/High, Severity/Blocker, Type/Bug

#538 Rename Testgrid Framework to Testgrid Project in poms
  automation/pom.xml
  common/pom.xml
  core/pom.xml
  dao/pom.xml
  deployment/pom.xml
  distribution/pom.xml
  infrastructure/pom.xml
  issue_template.md
  logging/pom.xml
  pom.xml
  pull_request_template.md
  reporting/pom.xml
  test/coverage/pom.xml
  web/pom.xml
Labels: Type/Improvement

#540 Gracefully handle failures in each step of product deployment verification.
  common/src/main/java/org/wso2/testgrid/common/DeploymentCreationResult.java
  common/src/main/java/org/wso2/testgrid/common/InfrastructureProvisionResult.java
  core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java
  core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
  core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java
  core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java
  core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java
  core/src/test/resources/test-plan-01.yaml
  core/src/test/resources/testng.xml
  core/src/test/resources/workspace/deployment/deploy.sh
  core/src/test/resources/workspace/infrastructure/infra-destroy.sh
  core/src/test/resources/workspace/infrastructure/infra-provision.sh
  core/src/test/resources/workspace/testgrid.yaml
  deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
  infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
  infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java
Labels: Priority/Highest, Severity/Critical, Type/New Feature

#545 Fix incorrect redirection to the login page when downloading a Test-log file
  web/src/main/react-dashboard/src/components/TestRunView.js
Labels: Severity/Blocker, Type/Bug

#563 Send the workspace as a property into the scenario test scripts.
  automation/pom.xml
  automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java
  automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
  automation/src/test/java/org/wso2/testgrid/automation/executor/JMeterExecutorTest.java
  automation/src/test/java/org/wso2/testgrid/automation/executor/TestExecutorFactoryTest.java
  automation/src/test/resources/testng.xml
  common/src/main/java/org/wso2/testgrid/common/DeploymentCreationResult.java
  common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java
  common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java
  common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java
  core/src/main/java/org/wso2/testgrid/core/Main.java
  core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java
  core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java
  core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java
  core/src/test/resources/workspace/scenarioTests/solution01/jmeter/file-existence-verifier.jmx
  core/src/test/resources/workspace/scenarioTests/solution01/resources/user.properties
  deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
  infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java
  infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/AMIMapper.java
  reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
  web/src/main/java/org/wso2/testgrid/web/api/InfrastructureAdderService.java
  web/src/main/java/org/wso2/testgrid/web/api/LogEventSocketMediator.java
  web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
Labels: Severity/Blocker, Type/Improvement

#592 Fix build issue due to unused imports
  automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
Labels: Type/Task
