Repository wso2/testgrid, pull requests merged in 2018-02, with the labels that each got.

#470 Use stack ID instead of stack name for describing stacks
  infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
Labels: Priority/High, Severity/Major, Type/Bug

#485 Generate final report using the latest test run for each infra combination
  reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
Labels: Priority/Highest, Severity/Critical, Type/Bug

#489 Fix failing persistence for long failure massages in test cases
  automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
Labels: Priority/Highest, Severity/Blocker, Type/Improvement

#503 Fix build failure due to missing DeploymentPatternConfig class
  core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
  core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java
  deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java
  deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
Labels: Type/Bug

#520 Set COMPONENT_ECS as the node label for continuous-delivery pipeline
  jenkins-pipelines/continuous-delivery/Jenkinsfile
Labels: Priority/Highest, Severity/Blocker, Type/Improvement

#516 Reduce verbosity in testgrid console output
  distribution/bin/log4j2.xml
Labels: Type/Improvement
